motd=§6Towny Kingdoms §8| §fSurvival, Economy, Nations
max-players=100
online-mode=true
difficulty=normal
gamemode=survival
pvp=true
spawn-protection=16
view-distance=8
simulation-distance=6
allow-nether=true
allow-flight=false
enable-command-block=false
enforce-secure-profile=false
