package dev.mooncode.townycore;

import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.configuration.file.*;import org.bukkit.entity.Player;import org.bukkit.event.*;import org.bukkit.event.block.BlockBreakEvent;import org.bukkit.event.inventory.InventoryClickEvent;import org.bukkit.event.player.PlayerJoinEvent;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import org.bukkit.plugin.java.JavaPlugin;import java.io.*;import java.util.*;

public final class MoonTownyCore extends JavaPlugin implements Listener,CommandExecutor{
  private File dataFile; private FileConfiguration data; private final Random rnd=new Random();
  private static final String MAIN="§8AyKasaba Ana Menü", CRATES="§8Kasalar", QUESTS="§8Görevler", MARKET="§8Market";
  public void onEnable(){saveDefaultConfig(); loadData(); Bukkit.getPluginManager().registerEvents(this,this); for(String c:List.of("menu","seviye","rtp","kasalar","gorevler","market","moonadmin")) Objects.requireNonNull(getCommand(c)).setExecutor(this); Bukkit.getScheduler().runTaskTimer(this,()->Bukkit.getOnlinePlayers().forEach(p->addXp(p,2)),1200,1200);}
  public void onDisable(){saveData();}
  private void loadData(){dataFile=new File(getDataFolder(),"players.yml"); if(!dataFile.exists()){dataFile.getParentFile().mkdirs(); try{dataFile.createNewFile();}catch(IOException ignored){}} data=YamlConfiguration.loadConfiguration(dataFile);} private void saveData(){try{data.save(dataFile);}catch(IOException e){getLogger().warning(e.getMessage());}}
  @EventHandler public void join(PlayerJoinEvent e){Player p=e.getPlayer(); p.sendMessage(c(pref()+"&aHoş geldin! &7/menu ile başlayabilirsin.")); if(!data.contains(path(p,"keys.vote"))) {data.set(path(p,"keys.vote"),2); data.set(path(p,"quest.blocks"),0); saveData();}}
  public boolean onCommand(CommandSender s,Command cmd,String label,String[] a){ if(!(s instanceof Player p)){s.sendMessage("Oyuncu komutu.");return true;} switch(label.toLowerCase()){case "menu"->openMain(p); case "seviye"->p.sendMessage(c(pref()+"Seviye &e"+level(p)+" &8| &7XP &b"+xp(p))); case "rtp"->rtp(p); case "kasalar"->openCrates(p); case "gorevler"->openQuests(p); case "market"->openMarket(p); case "moonadmin"->{ if(!p.hasPermission("moontowny.admin"))return true; if(a.length>=3&&a[0].equalsIgnoreCase("key")){data.set(path(p,"keys."+a[1]),key(p,a[1])+Integer.parseInt(a[2])); saveData(); p.sendMessage(c(pref()+"Anahtar eklendi."));} else if(a.length>=2&&a[0].equalsIgnoreCase("xp")){addXp(p,Integer.parseInt(a[1])); p.sendMessage(c(pref()+"XP eklendi."));}}} return true;}
  private void openMain(Player p){Inventory i=inv(MAIN,27); i.setItem(10,it(Material.GRASS_BLOCK,"&aRTP","&7Güvenli rastgele ışınlan.")); i.setItem(11,it(Material.CHEST,"&dKasalar","&7Oy, kraliyet ve sezon ödülleri.")); i.setItem(13,it(Material.BOOK,"&eGörevler","&7Günlük ilerleme ve ödül.")); i.setItem(15,it(Material.EMERALD,"&aMarket","&7Ücretsiz temel market.")); i.setItem(16,it(Material.OAK_SIGN,"&6Towny Rehberi","&e/t new <isim> &7kasaba kurar","&e/t claim &7arazi alır")); p.openInventory(i);} 
  private void openCrates(Player p){Inventory i=inv(CRATES,27); i.setItem(11,it(Material.TRIPWIRE_HOOK,"&aOy Kasası","&7Anahtar: &e"+key(p,"vote"),"&7Tıkla ve ödül al.")); i.setItem(13,it(Material.GOLDEN_APPLE,"&6Kraliyet Kasası","&7Anahtar: &e"+key(p,"royal"))); i.setItem(15,it(Material.AMETHYST_SHARD,"&dSezon Kasası","&7Anahtar: &e"+key(p,"seasonal"))); p.openInventory(i);} 
  private void openQuests(Player p){Inventory i=inv(QUESTS,27); int b=data.getInt(path(p,"quest.blocks")); i.setItem(13,it(Material.DIAMOND_PICKAXE,"&bMadenci Görevi","&7Blok kır: &e"+b+"&7/100","&aTamamlayınca 1 oy anahtarı + XP")); p.openInventory(i);} 
  private void openMarket(Player p){Inventory i=inv(MARKET,27); i.setItem(10,it(Material.OAK_LOG,"&6Odun Paketi","&7Ücretsiz başlangıç desteği.")); i.setItem(12,it(Material.COOKED_BEEF,"&cYemek Paketi","&7Ücretsiz başlangıç desteği.")); i.setItem(14,it(Material.IRON_PICKAXE,"&fDemir Kazma","&7Başlangıç aracı.")); i.setItem(16,it(Material.TORCH,"&eMeşale Paketi","&7Maden için.")); p.openInventory(i);} 
  @EventHandler public void click(InventoryClickEvent e){ if(!(e.getWhoClicked() instanceof Player p)||e.getCurrentItem()==null)return; String t=e.getView().getTitle(); if(!List.of(MAIN,CRATES,QUESTS,MARKET).contains(t))return; e.setCancelled(true); Material m=e.getCurrentItem().getType(); if(t.equals(MAIN)){if(m==Material.GRASS_BLOCK)rtp(p); else if(m==Material.CHEST)openCrates(p); else if(m==Material.BOOK)openQuests(p); else if(m==Material.EMERALD)openMarket(p);} else if(t.equals(CRATES)){openKey(p,m);} else if(t.equals(MARKET)){giveMarket(p,m);} }
  @EventHandler public void block(BlockBreakEvent e){Player p=e.getPlayer(); data.set(path(p,"quest.blocks"),data.getInt(path(p,"quest.blocks"))+1); if(data.getInt(path(p,"quest.blocks"))==100){data.set(path(p,"keys.vote"),key(p,"vote")+1); addXp(p,150); p.sendMessage(c(pref()+"&bMadenci görevi tamamlandı! &a+1 Oy Anahtarı"));} saveData();}
  private void rtp(Player p){World w=p.getWorld(); for(int n=0;n<30;n++){int x=rnd.nextInt(6000)-3000,z=rnd.nextInt(6000)-3000,y=w.getHighestBlockYAt(x,z)+1; Location l=new Location(w,x+0.5,y,z+0.5); if(l.getBlock().getType().isAir()){p.teleport(l); p.sendMessage(c(pref()+"&aRTP başarılı.")); return;}} p.sendMessage(c(pref()+"&cGüvenli konum bulunamadı."));}
  private void openKey(Player p,Material m){String k=m==Material.TRIPWIRE_HOOK?"vote":m==Material.GOLDEN_APPLE?"royal":m==Material.AMETHYST_SHARD?"seasonal":""; if(k.isEmpty())return; if(key(p,k)<1){p.sendMessage(c(pref()+"&cBu kasa için anahtarın yok."));return;} data.set(path(p,"keys."+k),key(p,k)-1); addXp(p, k.equals("vote")?40:120); p.getInventory().addItem(new ItemStack(k.equals("vote")?Material.DIAMOND:k.equals("royal")?Material.NETHERITE_SCRAP:Material.EMERALD, k.equals("vote")?2:1)); saveData(); p.sendMessage(c(pref()+"&aKasa açıldı, ödül envanterine eklendi."));}
  private void giveMarket(Player p,Material m){ItemStack item=switch(m){case OAK_LOG->new ItemStack(Material.OAK_LOG,32); case COOKED_BEEF->new ItemStack(Material.COOKED_BEEF,16); case IRON_PICKAXE->new ItemStack(Material.IRON_PICKAXE,1); case TORCH->new ItemStack(Material.TORCH,32); default->null;}; if(item!=null){p.getInventory().addItem(item); p.sendMessage(c(pref()+"&aÜrün verildi."));}}
  private Inventory inv(String title,int size){return Bukkit.createInventory(null,size,title);} private ItemStack it(Material m,String name,String... lore){ItemStack x=new ItemStack(m); ItemMeta im=x.getItemMeta(); im.setDisplayName(c(name)); im.setLore(Arrays.stream(lore).map(this::c).toList()); x.setItemMeta(im); return x;} private String path(Player p,String k){return p.getUniqueId()+"."+k;} private int xp(Player p){return data.getInt(path(p,"xp"));} private int key(Player p,String k){return data.getInt(path(p,"keys."+k));} private void addXp(Player p,int v){data.set(path(p,"xp"),xp(p)+v); saveData();} private int level(Player p){return Math.max(1,(int)Math.sqrt(xp(p)/100.0)+1);} private String pref(){return "&6AyKasaba &8» &f";} private String c(String s){return ChatColor.translateAlternateColorCodes('&',s);} }
