package dev.mooncode.townycore;

import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.configuration.file.*;import org.bukkit.entity.Player;import org.bukkit.event.*;import org.bukkit.event.block.*;import org.bukkit.event.inventory.InventoryClickEvent;import org.bukkit.event.player.PlayerJoinEvent;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import org.bukkit.plugin.java.JavaPlugin;import java.io.*;import java.util.*;

public final class MoonTownyCore extends JavaPlugin implements Listener,CommandExecutor{
  private File dataFile; private FileConfiguration data; private final Random rnd=new Random();
  private static final String MAIN="§8AyKasaba Ana Menü", CRATES="§8Kasalar", QUESTS="§8Görevler", MARKET="§8Market", JOBS="§8İşler";
  public void onEnable(){saveDefaultConfig(); loadData(); Bukkit.getPluginManager().registerEvents(this,this); for(String c:List.of("menu","seviye","para","isler","rtp","kasalar","gorevler","market","setwarp","warp","gunluk","moonadmin")) Objects.requireNonNull(getCommand(c)).setExecutor(this); Bukkit.getScheduler().runTaskTimer(this,()->Bukkit.getOnlinePlayers().forEach(p->addXp(p,2)),1200,1200);}
  public void onDisable(){saveData();}
  private void loadData(){dataFile=new File(getDataFolder(),"players.yml"); if(!dataFile.exists()){dataFile.getParentFile().mkdirs(); try{dataFile.createNewFile();}catch(IOException ignored){}} data=YamlConfiguration.loadConfiguration(dataFile);} private void saveData(){try{data.save(dataFile);}catch(IOException e){getLogger().warning(e.getMessage());}}
  @EventHandler public void join(PlayerJoinEvent e){Player p=e.getPlayer(); p.sendMessage(c(pref()+"&aHoş geldin! &7/menu ile başlayabilirsin.")); if(!data.contains(path(p,"money"))){data.set(path(p,"money"),250);data.set(path(p,"keys.vote"),2);data.set(path(p,"quest.blocks"),0);saveData();}}
  public boolean onCommand(CommandSender s,Command cmd,String label,String[] a){ if(!(s instanceof Player p)){s.sendMessage("Oyuncu komutu.");return true;} switch(label.toLowerCase()){case "menu"->openMain(p); case "seviye"->p.sendMessage(c(pref()+"Seviye &e"+level(p)+" &8| &7XP &b"+xp(p))); case "para"->p.sendMessage(c(pref()+"Bakiye: &a$"+money(p))); case "isler"->openJobs(p); case "rtp"->rtp(p); case "kasalar"->openCrates(p); case "gorevler"->openQuests(p); case "market"->openMarket(p); case "gunluk"->daily(p); case "setwarp"->{if(a.length<1){p.sendMessage(c(pref()+"&cKullanım: /setwarp <isim>"));return true;} setWarp(p,a[0]);} case "warp"->{if(a.length<1){p.sendMessage(c(pref()+"&cKullanım: /warp <isim>"));return true;} goWarp(p,a[0]);} case "moonadmin"->admin(p,a);} return true;}
  private void admin(Player p,String[] a){if(!p.hasPermission("moontowny.admin"))return; if(a.length>=2&&a[0].equalsIgnoreCase("xp")){addXp(p,Integer.parseInt(a[1]));p.sendMessage(c(pref()+"XP eklendi."));} else if(a.length>=2&&a[0].equalsIgnoreCase("money")){addMoney(p,Integer.parseInt(a[1]));p.sendMessage(c(pref()+"Para eklendi."));} else if(a.length>=3&&a[0].equalsIgnoreCase("key")){data.set(path(p,"keys."+a[1]),key(p,a[1])+Integer.parseInt(a[2]));saveData();p.sendMessage(c(pref()+"Anahtar eklendi."));}}
  private void openMain(Player p){Inventory i=inv(MAIN,27); i.setItem(10,it(Material.GRASS_BLOCK,"&aRTP","&7Güvenli rastgele ışınlan.")); i.setItem(11,it(Material.CHEST,"&dKasalar","&7Ödül kasaları.")); i.setItem(12,it(Material.IRON_PICKAXE,"&6İşler","&7Meslek seç ve para kazan.")); i.setItem(13,it(Material.BOOK,"&eGörevler","&7Günlük ilerleme ve ödül.")); i.setItem(15,it(Material.EMERALD,"&aMarket","&7Dengeli market.")); i.setItem(16,it(Material.OAK_SIGN,"&6Towny Rehberi","&e/t new <isim>","&e/t claim")); p.openInventory(i);} 
  private void openJobs(Player p){Inventory i=inv(JOBS,27); i.setItem(10,it(Material.DIAMOND_PICKAXE,"&bMadenci","&7Blok kırınca para/XP.")); i.setItem(12,it(Material.IRON_AXE,"&6Oduncu","&7Ağaç kırınca para/XP.")); i.setItem(14,it(Material.WHEAT,"&eÇiftçi","&7Ekin hasadında para/XP.")); i.setItem(16,it(Material.BOW,"&cAvcı","&7Yakında eklenecek.")); p.openInventory(i);} 
  private void openCrates(Player p){Inventory i=inv(CRATES,27); i.setItem(11,it(Material.TRIPWIRE_HOOK,"&aOy Kasası","&7Anahtar: &e"+key(p,"vote"))); i.setItem(13,it(Material.GOLDEN_APPLE,"&6Kraliyet Kasası","&7Anahtar: &e"+key(p,"royal"))); i.setItem(15,it(Material.AMETHYST_SHARD,"&dSezon Kasası","&7Anahtar: &e"+key(p,"seasonal"))); p.openInventory(i);} 
  private void openQuests(Player p){Inventory i=inv(QUESTS,27); int b=data.getInt(path(p,"quest.blocks")); i.setItem(13,it(Material.DIAMOND_PICKAXE,"&bMadenci Görevi","&7Blok kır: &e"+b+"&7/100","&aÖdül: $500 + 1 oy anahtarı")); p.openInventory(i);} 
  private void openMarket(Player p){Inventory i=inv(MARKET,27); i.setItem(10,it(Material.OAK_LOG,"&6Odun Paketi","&7Fiyat: &a$80")); i.setItem(12,it(Material.COOKED_BEEF,"&cYemek Paketi","&7Fiyat: &a$60")); i.setItem(14,it(Material.IRON_PICKAXE,"&fDemir Kazma","&7Fiyat: &a$250")); i.setItem(16,it(Material.TORCH,"&eMeşale Paketi","&7Fiyat: &a$40")); p.openInventory(i);} 
  @EventHandler public void click(InventoryClickEvent e){ if(!(e.getWhoClicked() instanceof Player p)||e.getCurrentItem()==null)return; String t=e.getView().getTitle(); if(!List.of(MAIN,CRATES,QUESTS,MARKET,JOBS).contains(t))return; e.setCancelled(true); Material m=e.getCurrentItem().getType(); if(t.equals(MAIN)){if(m==Material.GRASS_BLOCK)rtp(p); else if(m==Material.CHEST)openCrates(p); else if(m==Material.IRON_PICKAXE)openJobs(p); else if(m==Material.BOOK)openQuests(p); else if(m==Material.EMERALD)openMarket(p);} else if(t.equals(CRATES))openKey(p,m); else if(t.equals(MARKET))buy(p,m); else if(t.equals(JOBS))selectJob(p,m);}
  @EventHandler public void block(BlockBreakEvent e){Player p=e.getPlayer(); data.set(path(p,"quest.blocks"),data.getInt(path(p,"quest.blocks"))+1); String job=data.getString(path(p,"job"),""); if(job.equals("miner")&&e.getBlock().getType().name().contains("ORE")){addMoney(p,12);addXp(p,4);} if(job.equals("woodcutter")&&e.getBlock().getType().name().contains("LOG")){addMoney(p,6);addXp(p,2);} if(data.getInt(path(p,"quest.blocks"))==100){data.set(path(p,"keys.vote"),key(p,"vote")+1);addMoney(p,500);addXp(p,150);p.sendMessage(c(pref()+"&bMadenci görevi tamamlandı! &a+$500 +1 Oy Anahtarı"));} saveData();}
  @EventHandler public void harvest(BlockBreakEvent e){Material m=e.getBlock().getType(); if(data.getString(path(e.getPlayer(),"job"),"").equals("farmer")&&(m==Material.WHEAT||m==Material.CARROTS||m==Material.POTATOES)){addMoney(e.getPlayer(),5);addXp(e.getPlayer(),2);}}
  private void selectJob(Player p,Material m){String j=m==Material.DIAMOND_PICKAXE?"miner":m==Material.IRON_AXE?"woodcutter":m==Material.WHEAT?"farmer":""; if(!j.isEmpty()){data.set(path(p,"job"),j);saveData();p.sendMessage(c(pref()+"&aİş seçildi: &e"+j));}}
  private void rtp(Player p){World w=p.getWorld(); for(int n=0;n<30;n++){int x=rnd.nextInt(6000)-3000,z=rnd.nextInt(6000)-3000,y=w.getHighestBlockYAt(x,z)+1; Location l=new Location(w,x+.5,y,z+.5); if(l.getBlock().getType().isAir()){p.teleport(l);p.sendMessage(c(pref()+"&aRTP başarılı."));return;}} p.sendMessage(c(pref()+"&cGüvenli konum bulunamadı."));}
  private void openKey(Player p,Material m){String k=m==Material.TRIPWIRE_HOOK?"vote":m==Material.GOLDEN_APPLE?"royal":m==Material.AMETHYST_SHARD?"seasonal":""; if(k.isEmpty())return; if(key(p,k)<1){p.sendMessage(c(pref()+"&cAnahtarın yok."));return;} data.set(path(p,"keys."+k),key(p,k)-1); addMoney(p,k.equals("vote")?150:700); addXp(p,k.equals("vote")?40:120); p.getInventory().addItem(new ItemStack(k.equals("vote")?Material.DIAMOND:k.equals("royal")?Material.NETHERITE_SCRAP:Material.EMERALD,k.equals("vote")?2:1)); saveData(); p.sendMessage(c(pref()+"&aKasa açıldı."));}
  private void buy(Player p,Material m){int price=switch(m){case OAK_LOG->80;case COOKED_BEEF->60;case IRON_PICKAXE->250;case TORCH->40;default->-1;}; ItemStack item=switch(m){case OAK_LOG->new ItemStack(Material.OAK_LOG,32);case COOKED_BEEF->new ItemStack(Material.COOKED_BEEF,16);case IRON_PICKAXE->new ItemStack(Material.IRON_PICKAXE,1);case TORCH->new ItemStack(Material.TORCH,32);default->null;}; if(item!=null&&takeMoney(p,price)){p.getInventory().addItem(item);p.sendMessage(c(pref()+"&aSatın alındı."));}}
  private void daily(Player p){long now=System.currentTimeMillis(), last=data.getLong(path(p,"daily")); if(now-last<86400000){p.sendMessage(c(pref()+"&cGünlük ödülü zaten aldın."));return;} data.set(path(p,"daily"),now); addMoney(p,300); data.set(path(p,"keys.vote"),key(p,"vote")+1); saveData(); p.sendMessage(c(pref()+"&aGünlük ödül: $300 + 1 Oy Anahtarı"));}
  private void setWarp(Player p,String n){data.set("warps."+n+".world",p.getWorld().getName());data.set("warps."+n+".x",p.getLocation().getX());data.set("warps."+n+".y",p.getLocation().getY());data.set("warps."+n+".z",p.getLocation().getZ());saveData();p.sendMessage(c(pref()+"&aWarp oluşturuldu: &e"+n));}
  private void goWarp(Player p,String n){if(!data.contains("warps."+n)){p.sendMessage(c(pref()+"&cWarp yok."));return;} World w=Bukkit.getWorld(data.getString("warps."+n+".world")); p.teleport(new Location(w,data.getDouble("warps."+n+".x"),data.getDouble("warps."+n+".y"),data.getDouble("warps."+n+".z")));}
  private Inventory inv(String title,int size){return Bukkit.createInventory(null,size,title);} private ItemStack it(Material m,String name,String... lore){ItemStack x=new ItemStack(m); ItemMeta im=x.getItemMeta(); im.setDisplayName(c(name)); im.setLore(Arrays.stream(lore).map(this::c).toList()); x.setItemMeta(im); return x;} private String path(Player p,String k){return p.getUniqueId()+"."+k;} private int xp(Player p){return data.getInt(path(p,"xp"));} private int money(Player p){return data.getInt(path(p,"money"));} private int key(Player p,String k){return data.getInt(path(p,"keys."+k));} private void addXp(Player p,int v){data.set(path(p,"xp"),xp(p)+v); saveData();} private void addMoney(Player p,int v){data.set(path(p,"money"),money(p)+v); saveData();} private boolean takeMoney(Player p,int v){if(money(p)<v){p.sendMessage(c(pref()+"&cYetersiz para."));return false;} data.set(path(p,"money"),money(p)-v); saveData(); return true;} private int level(Player p){return Math.max(1,(int)Math.sqrt(xp(p)/100.0)+1);} private String pref(){return "&6AyKasaba &8» &f";} private String c(String s){return ChatColor.translateAlternateColorCodes('&',s);} }
